name: Rust CI Automatizado

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Inicializar proyecto si no existe
        run: |
          if [ ! -f "Cargo.toml" ]; then
            echo "Cargo.toml no encontrado, creando proyecto..."
            cargo init
          fi

      - name: Compilar y Ejecutar
        run: cargo run
