name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Compilar y Ejecutar
        run: cargo run
